const ROOT = '';

export const FETCH_USERS_REQUEST = `${ROOT}/FETCH_USERS_REQUEST`;
export const FETCH_USERS_FAILURE = `${ROOT}/FETCH_USERS_FAILURE`;
export const FETCH_USERS_SUCCESS = `${ROOT}/FETCH_USERS_SUCCESS`;
