const ROOT = '';

export const FETCH_SECTION_HEADER_REQUEST = `${ROOT}/FETCH_SECTION_HEADER_REQUEST`;
export const FETCH_SECTION_HEADER_FAILURE = `${ROOT}/FETCH_SECTION_HEADER_FAILURE`;
export const FETCH_SECTION_HEADER_SUCCESS = `${ROOT}/FETCH_SECTION_HEADER_SUCCESS`;
