const ROOT = '';

export const FETCH_TOKEN_REQUEST = `${ROOT}/FETCH_TOKEN_REQUEST`;
export const FETCH_TOKEN_FAILURE = `${ROOT}/FETCH_TOKEN_FAILURE`;
export const FETCH_TOKEN_SUCCESS = `${ROOT}/FETCH_TOKEN_SUCCESS`;
