const ROOT = '';

export const FETCH_SECTION_REQUEST = `${ROOT}/FETCH_SECTION_REQUEST`;
export const FETCH_SECTION_FAILURE = `${ROOT}/FETCH_SECTION_FAILURE`;
export const FETCH_SECTION_SUCCESS = `${ROOT}/FETCH_SECTION_SUCCESS`;
